### PR TITLE
Updates 

### PR DESCRIPTION
**Pull request by l3op**

### CODE REVIEW

**Comment by l3op** [comment]
Hello, I'd like to suggest to keep the script part and get rid of 
> DIALOG_WEB_LENGHT_MIN/DIALOG_WEB_LENGHT_MAX. 

variables. and i'll keep updating the archive everytime when a new language added. Unless you want me to make the change! i'm here always.

**Comment by strasharo** [comment]
Okay, there's another way to solve it. We can make the main script echo the content of the messages_*.js into the file and still use the variables instead of bundling the file in the archive. What do you think about that approach? :)

**Comment by l3op** [comment]
Okay then, Let's stick with first suggestion. It's the perfect approach.

**Comment by strasharo** [comment]
Thanks a lot @l3op , awesome contribution. :)

**Comment by l3op** [comment]
Anytime mate.

**Pull request merged**
