### PR TITLE
Update fluxion

### PR DESCRIPTION
**Pull request by kip2sharkTD**
Had to remove the . in front ./lib/airmon/airmon of the lines this now executes with no errors with that particular issue.  The command would not run.  Lines 615, 616, 652, 653, and 678

### CODE REVIEW

**Comment by kip2sharkTD** [comment]
can someone with write access please commit this change?

**Comment by deltaxflux** [comment]
**That doesn't make any sense**. If you want to change it for some reason. Remove also the /
like ./lib/ to lib. 
Your change doesn't effect anything.

**Comment by kip2sharkTD** [comment]
There are a couple of issues with the code.  
1.  The location or airmon is not located in /lib/airmon it is located where the user decides to place the fluxion directory.
2.  airmon is not copied from the fluxion directory to the /lib/airmon directory which is a strange place to put the file as it is not a library.  
3.  in your current state your recommendation of just using lib/airmon/airmon wont work either as it will attempt to use the cwd and if it is not / first, error again.

Thoughts?

**Comment by deltaxflux** [comment]
I think we misunderstood us. The lib folder is located inside the fluxion directory. 
You can double check it with
```
$(pwd)/lib/airmon/airmon
``` 
_e.g. /home/deltax/fluxion/lib/airmon_

**Comment by kip2sharkTD** [comment]
Hello Deltax:

Will check in a few.  Thanks for getting back.

Kip

**Comment by dcomaster** [comment]
hello deltax
i get this issue when i updated fluxion on my pc : 

2] Error: your wireless card  isn't supported  
Do you want exit? [Yes / No]:y
/root/Downloads/fluxion-master/fluxion: line 795: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
 [1]	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	 	  100%	 

 (*) 
i try everything but nothing works....plz help!!!!

**Comment by deltaxflux** [comment]
This is not for issues

**Comment by dcomaster** [comment]
Plz...tell me ..what can i do to resolve this?

**Comment by deltaxflux** [comment]
no

**Pull request closed without merging**
